"""Mappatura codici alert Opel → nome leggibile (estratti dall'app MyOpel)."""

ALERT_CODES: dict[int, str] = {
    0: "Pressione olio motore anomala",
    1: "Temperatura motore troppo elevata",
    3: "Anomalia impianto frenante",
    4: "Livello liquido freni insufficiente",
    5: "Anomalia servosterzo",
    6: "Livello liquido di raffreddamento insufficiente",
    7: "Anomalia assistenza cambio corsia",
    8: "Livello olio motore insufficiente",
    10: "Porta anteriore sinistra aperta",
    11: "Porta anteriore destra aperta",
    12: "Porta posteriore sinistra aperta",
    13: "Motore",
    14: "Tappo serbatoio carburante non bloccato",
    15: "Cofano aperto",
    16: "Lunotto posteriore aperto",
    17: "Anomalia ESP / ASR",
    18: "Anomalia batteria",
    20: "Anomalia del filtro gasolio",
    21: "Stadio avanzato di usura delle pastiglie dei freni",
    22: "Livello carburante basso",
    23: "Anomalia Airbag",
    25: "Anomalia del sistema antinquinamento",
    26: "Anomalia ABS",
    27: "Rischio di intasamento del filtro antiparticolato (FAP)",
    29: "Livello additivo del filtro antiparticolato insufficiente",
    30: "Temperatura olio cambio eccessiva",
    31: "Anomalia al sistema delle sospensioni",
    32: "Preriscaldamento/preaerazione disattivato: batteria scarica",
    33: "Preriscaldamento/preaerazione disattivato: carburante basso",
    34: "Controllare luce stop centrale",
    35: "Anomalia meccanismo tetto apribile",
    36: "Anomalia bloccasterzo",
    37: "Anomalia dell'antiavviamento elettronico",
    38: "Livello olio troppo alto",
    39: "Manovra tetto impossibile: temperatura sistema eccessiva",
    40: "Manovra tetto impossibile: avviare il motore",
    41: "Manovra tetto impossibile: inserire il freno a mano",
    42: "Guasto al sistema ibrido: Arresta il veicolo, consulta il manuale",
    43: "Regolazione automatica dei fari difettosa",
    44: "Anomalia del sistema di trazione ibrida",
    45: "Anomalia del sistema di trazione ibrida",
    46: "Livello liquido lavacristalli insufficiente",
    47: "Sostituire la batteria del telecomando",
    48: "Anomalia presa d'aria controllata",
    49: "Preriscaldamento/preaerazione disattivato: regolare l'orologio",
    50: "Anomalia collegamento rimorchio",
    52: "Pressione pneumatico/i insufficiente",
    53: "Sensore radar di guida sporco",
    57: "Modalità elettrica non disponibile: rigenerazione FAP in corso",
    59: "Pressione pneumatico insufficiente (Anteriore Sinistro)",
    60: "Pressione pneumatico insufficiente (Anteriore Destro)",
    61: "Pressione pneumatico insufficiente (Posteriore Sinistro)",
    62: "Pressione pneumatico insufficiente (Posteriore Destro)",
    63: "Anomalia luce di posizione (Anteriore Sinistra)",
    64: "Anomalia luce di posizione (Anteriore Destra)",
    65: "Anomalia luce di posizione (Posteriore Destra)",
    66: "Anomalia luce di posizione (Posteriore Sinistra)",
    67: "Anomalia anabbaglianti",
    68: "Anomalia anabbaglianti",
    69: "Anomalia abbaglianti",
    70: "Anomalia abbaglianti",
    71: "Anomalia luce di stop (Posteriore Destra)",
    72: "Anomalia luce di stop (Posteriore Sinistra)",
    73: "Anomalia fendinebbia",
    74: "Anomalia fendinebbia anteriori",
    75: "Anomalia fendinebbia posteriori (Destra)",
    76: "Anomalia fendinebbia posteriori",
    77: "Anomalia indicatore di direzione (Anteriore Destro)",
    78: "Anomalia indicatore di direzione (Posteriore Destro)",
    79: "Anomalia indicatore di direzione (Anteriore Sinistro)",
    80: "Anomalia indicatore di direzione (Posteriore Sinistro)",
    81: "Anomalia luce di retromarcia",
    82: "Anomalia luce di retromarcia (Sinistra)",
    90: "Cofano attivo difettoso",
    91: "Anomalia sistema di parcheggio assistito",
    92: "Sistema di rilevamento parcheggio difettoso",
    94: "Pressione pneumatico insufficiente (Anteriore Sinistro)",
    95: "Pressione pneumatico insufficiente (Anteriore Destro)",
    96: "Pressione pneumatico insufficiente (Posteriore Destro)",
    97: "Pressione pneumatico insufficiente (Posteriore Sinistro)",
    98: "Spegnere i fari",
    100: "Anomalia antinquinamento",
    101: "Anomalia antinquinamento: non avviare",
    102: "Anomalia antinquinamento",
    103: "Cintura passeggero post. sinistra non allacciata",
    104: "Cintura passeggero post. centrale non allacciata",
    106: "Inserire cambio automatico in posizione P",
    107: "Rischio ghiaccio",
    108: "Porta anteriore destra aperta",
    109: "Porta anteriore sinistra aperta",
    110: "Porta posteriore destra aperta",
    111: "Porta posteriore sinistra aperta",
    112: "Porta del bagagliaio aperta",
    113: "Anomalia sistema rilevamento rischio collisione",
    114: "Lunotto posteriore aperto",
    115: "Tappo serbatoio carburante non bloccato",
    123: "Anomalia sistema freno di stazionamento",
    124: "Alettone mobile difettoso: velocità limitata",
    125: "Anomalia del sistema di frenata automatica",
    126: "Anomalia luce/i di curva",
    133: "Anomalia al cambio",
    137: "Anomalia sistema avviso superamento corsia",
    139: "Pressione pneumatico insufficiente",
    140: "Comando freno di stazionamento difettoso",
    141: "Malfunzionamento generale del motore",
    142: "Anomalia della sospensione: velocità limitata a 90 km/h",
    148: "Anomalia sensore pressione pneumatico (Anteriore Sinistro)",
    149: "Anomalia sensore pressione pneumatico (Anteriore Destro)",
    150: "Anomalia sensore pressione pneumatico (Posteriore Destro)",
    151: "Anomalia sensore pressione pneumatico (Posteriore Sinistro)",
    152: "Anomalia della sospensione: limitare a 90 km/h",
    153: "Anomalia servosterzo",
    156: "Anomalia misurazione distanza intervehicolare",
    157: "Anomalia motore: fermare il veicolo",
    158: "Anomalia assistenza mantenimento in corsia",
    159: "Anomalia monitoraggio pressione pneumatici",
    160: "Pneumatico posteriore destro sgonfio",
    161: "Pneumatico posteriore sinistro sgonfio",
    162: "Pneumatico anteriore destro sgonfio",
    163: "Pneumatico anteriore sinistro sgonfio",
    164: "Frenata automatica disattivata",
    165: "Livello additivo antinquinamento insufficiente",
    166: "Livello additivo antinquinamento insufficiente",
    167: "Livello additivo antinquinamento insufficiente",
}
